#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE "$DB_NEW_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE "$DB_NEW_DATABASE" TO "$POSTGRES_USER";
EOSQL